name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub CLI
        run: gh version

      - name: Set up local repository
        run: |
          git config --global user.email "andr.ta.31@gmail.com"
          git config --global user.name "andrta31"
          git clone https://github.com/andretai/sandbox-pr-automation.git pr-auto

      - name: Commit changes
        run: |
          git status
          git checkout -b to_be_merged
          echo "new line" >> file.txt
          git add .
          git commit -m "Update file.txt"
          git push
        working-directory: ./pr-auto

      - name: Create pull request
        run: |
          gh pr create --title "Update file.txt" --body "Add new line to file.txt."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
