name: Create Pull Request

on:
  pull_request:
    branches:
    - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request Information
        run: |
          echo ${{ github.event.type }}
          echo ${{ github.event.headRefName }}
          echo ${{ github.event.baseRefName }}
          echo ${{ github.event.number }}
