name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub CLI
        run: gh version

      - name: Check GitHub Secrets (Caution)
        run: echo ${{ secrets.GITHUB_TOKEN }}
